2024-01-30 14:04:37,384 INFO    MainThread:74817 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-01-30 14:04:37,384 INFO    MainThread:74817 [wandb_setup.py:_flush():76] Configure stats pid to 74817
2024-01-30 14:04:37,384 INFO    MainThread:74817 [wandb_setup.py:_flush():76] Loading settings from /Users/songzeyang/.config/wandb/settings
2024-01-30 14:04:37,384 INFO    MainThread:74817 [wandb_setup.py:_flush():76] Loading settings from /Users/songzeyang/Documents/GitHub/Data_Distill_with_NC/wandb/settings
2024-01-30 14:04:37,384 INFO    MainThread:74817 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'hyper_sweep_4_', 'entity': 'data-distillation-with-nc', 'root_dir': '/Users/songzeyang/Documents/GitHub/Data_Distill_with_NC', 'run_id': '7eu2xpjy', 'sweep_param_path': '/Users/songzeyang/Documents/GitHub/Data_Distill_with_NC/wandb/sweep-cr28hdxq/config-7eu2xpjy.yaml', 'sweep_id': 'cr28hdxq'}
2024-01-30 14:04:37,384 INFO    MainThread:74817 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-01-30 14:04:37,384 INFO    MainThread:74817 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-30 14:04:37,384 INFO    MainThread:74817 [wandb_init.py:_log_setup():524] Logging user logs to /Users/songzeyang/Documents/GitHub/Data_Distill_with_NC/wandb/run-20240130_140437-7eu2xpjy/logs/debug.log
2024-01-30 14:04:37,384 INFO    MainThread:74817 [wandb_init.py:_log_setup():525] Logging internal logs to /Users/songzeyang/Documents/GitHub/Data_Distill_with_NC/wandb/run-20240130_140437-7eu2xpjy/logs/debug-internal.log
2024-01-30 14:04:37,385 INFO    MainThread:74817 [wandb_init.py:_jupyter_setup():470] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x109845e50>
2024-01-30 14:04:37,385 INFO    MainThread:74817 [wandb_init.py:init():564] calling init triggers
2024-01-30 14:04:37,385 INFO    MainThread:74817 [wandb_init.py:init():571] wandb.init called with sweep_config: {'batch_size': 64, 'depth': 4, 'learning_rate': 0.1, 'model': 'MLP', 'optimizer': 'Adam', 'width': 4096}
config: {'method': 'grid', 'metric': {'name': 'loss', 'goal': 'minimize'}, 'parameters': {'model': {'values': ['MLP', 'ResNet18_adapt']}, 'learning_rate': {'values': [0.1, 0.05, 0.001]}, 'optimizer': {'values': ['Adam', 'SGD', 'LBFGS']}, 'width': {'values': [1024, 2048, 4096]}, 'depth': {'values': [4, 8, 12]}, 'batch_size': {'values': [64, 256, 2048]}}}
2024-01-30 14:04:37,385 INFO    MainThread:74817 [wandb_init.py:init():614] starting backend
2024-01-30 14:04:37,385 INFO    MainThread:74817 [wandb_init.py:init():618] setting up manager
2024-01-30 14:04:37,390 INFO    MainThread:74817 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-01-30 14:04:37,391 INFO    MainThread:74817 [wandb_init.py:init():624] backend started and connected
2024-01-30 14:04:37,398 INFO    MainThread:74817 [wandb_run.py:_config_callback():1342] config_cb None None {'batch_size': 64, 'depth': 4, 'learning_rate': 0.1, 'model': 'MLP', 'optimizer': 'Adam', 'width': 4096}
2024-01-30 14:04:37,404 INFO    MainThread:74817 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-01-30 14:04:37,404 INFO    MainThread:74817 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-01-30 14:04:37,404 INFO    MainThread:74817 [wandb_init.py:init():716] updated telemetry
2024-01-30 14:04:37,457 INFO    MainThread:74817 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-01-30 14:06:07,931 ERROR   MainThread:74817 [wandb_init.py:init():775] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-01-30 14:06:08,034 ERROR   MainThread:74817 [wandb_init.py:init():1188] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
          ^^^^^^^^^
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-01-30 14:18:27,835 INFO    MainThread:74817 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-01-30 14:18:27,836 INFO    MainThread:74817 [wandb_setup.py:_flush():76] Configure stats pid to 74817
2024-01-30 14:18:27,836 INFO    MainThread:74817 [wandb_setup.py:_flush():76] Loading settings from /Users/songzeyang/.config/wandb/settings
2024-01-30 14:18:27,836 INFO    MainThread:74817 [wandb_setup.py:_flush():76] Loading settings from /Users/songzeyang/Documents/GitHub/Data_Distill_with_NC/wandb/settings
2024-01-30 14:18:27,836 INFO    MainThread:74817 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'hyper_sweep_4_', 'entity': 'data-distillation-with-nc', 'root_dir': '/Users/songzeyang/Documents/GitHub/Data_Distill_with_NC', 'run_id': '7eu2xpjy', 'sweep_param_path': '/Users/songzeyang/Documents/GitHub/Data_Distill_with_NC/wandb/sweep-cr28hdxq/config-7eu2xpjy.yaml', 'sweep_id': 'cr28hdxq'}
2024-01-30 14:18:27,836 INFO    MainThread:74817 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-01-30 14:18:27,836 INFO    MainThread:74817 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-30 14:18:27,836 INFO    MainThread:74817 [wandb_init.py:_log_setup():524] Logging user logs to /Users/songzeyang/Documents/GitHub/Data_Distill_with_NC/wandb/run-20240130_141827-7eu2xpjy/logs/debug.log
2024-01-30 14:18:27,836 INFO    MainThread:74817 [wandb_init.py:_log_setup():525] Logging internal logs to /Users/songzeyang/Documents/GitHub/Data_Distill_with_NC/wandb/run-20240130_141827-7eu2xpjy/logs/debug-internal.log
2024-01-30 14:18:27,837 INFO    MainThread:74817 [wandb_init.py:init():564] calling init triggers
2024-01-30 14:18:27,837 INFO    MainThread:74817 [wandb_init.py:init():571] wandb.init called with sweep_config: {'batch_size': 64, 'depth': 4, 'learning_rate': 0.1, 'model': 'MLP', 'optimizer': 'Adam', 'width': 4096}
config: {'method': 'grid', 'metric': {'name': 'loss', 'goal': 'minimize'}, 'parameters': {'model': {'values': ['MLP', 'ResNet18_adapt']}, 'learning_rate': {'values': [0.1, 0.05, 0.001]}, 'optimizer': {'values': ['Adam', 'SGD', 'LBFGS']}, 'width': {'values': [1024, 2048, 4096]}, 'depth': {'values': [4, 8, 12]}, 'batch_size': {'values': [64, 256, 2048]}}}
2024-01-30 14:18:27,837 INFO    MainThread:74817 [wandb_init.py:init():614] starting backend
2024-01-30 14:18:27,837 INFO    MainThread:74817 [wandb_init.py:init():618] setting up manager
2024-01-30 14:18:27,843 INFO    MainThread:74817 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-01-30 14:18:27,843 INFO    MainThread:74817 [wandb_init.py:init():624] backend started and connected
2024-01-30 14:18:27,852 INFO    MainThread:74817 [wandb_run.py:_config_callback():1342] config_cb None None {'batch_size': 64, 'depth': 4, 'learning_rate': 0.1, 'model': 'MLP', 'optimizer': 'Adam', 'width': 4096}
2024-01-30 14:18:27,853 INFO    MainThread:74817 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-01-30 14:18:27,853 INFO    MainThread:74817 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-01-30 14:18:27,853 INFO    MainThread:74817 [wandb_init.py:init():716] updated telemetry
2024-01-30 14:18:27,900 INFO    MainThread:74817 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-01-30 14:19:58,354 ERROR   MainThread:74817 [wandb_init.py:init():775] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-01-30 14:19:58,493 ERROR   MainThread:74817 [wandb_init.py:init():1188] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
          ^^^^^^^^^
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
